#!/bin/bash

# This script parses file_info.txt (generated by Vivado export)
# and sources.f (for user RTL)
# to create a Makefile for compiling and simulating the design using xvlog/xvhdl/xelab/xsim.

# --- Configuration ---
BD_NAME="kv260" 
FILE_INFO="${BD_NAME}/xsim/file_info.txt"
RTL_INFO="sources.f"
OUTPUT_MAKEFILE="Makefile_Auto.mk"
SIM_WORK_DIR="output/work" # Simulation work library directory

echo "# Auto-generated simulation Makefile from $FILE_INFO and $RTL_INFO" > "${OUTPUT_MAKEFILE}"
echo "# Generated on $(date)" >> "${OUTPUT_MAKEFILE}"
echo "" >> "${OUTPUT_MAKEFILE}"

echo "# Define variables for pretty printing." >> "${OUTPUT_MAKEFILE}"
echo "ESC := \$(shell printf '\033')" >> "${OUTPUT_MAKEFILE}"
echo "YELLOW := \$(ESC)[33m" >> "${OUTPUT_MAKEFILE}"
echo "GREEN := \$(ESC)[32m" >> "${OUTPUT_MAKEFILE}"
echo "RED := \$(ESC)[31m" >> "${OUTPUT_MAKEFILE}"
echo "CYAN := \$(ESC)[36m" >> "${OUTPUT_MAKEFILE}"
echo "RESET := \$(ESC)[0m" >> "${OUTPUT_MAKEFILE}"
echo "" >> "${OUTPUT_MAKEFILE}"

# --- Store all unique include directories ---
declare -A unique_incdirs # Associative array to store unique directories
# Changed: Use an array to collect paths for ALL_INCLUDE_DIRS, then join with backslashes
ALL_INCLUDE_DIRS_TEMP=() 

COMPILE_COMMANDS=()
SOURCE_FILES=()
WORK_FILES=()
declare -A DEPENDENCIES_LIST

# Define the root directory where your custom RTL files are located
ROOT_RTL_DIR=$(dirname "${RTL_INFO}")
if [[ -z "$ROOT_RTL_DIR" ]]; then
    ROOT_RTL_DIR="." # If sources.f is in current dir, set root to '.'
fi

echo "Parsing $FILE_INFO for IP sources..."

# Define the root directory where all IP source files are actually located
SOURCE_FILE_ROOT_IP="${BD_NAME}/xsim"

while IFS=',' read -r filename lang lib_name vivado_orig_filepath rest_of_line; do
    # Skip empty lines or lines that don't look like file entries
    if [[ -z "$filename" ]]; then
        continue
    fi

    # Find the actual path of the file based on its filename
    # Use 'find' to search recursively in SOURCE_FILE_ROOT_IP
    actual_filepath=$(find "${SOURCE_FILE_ROOT_IP}" -name "${filename}" 2>/dev/null | head -n 1)

    if [[ -z "$actual_filepath" ]]; then
        echo "Error: Could not find IP file '$filename' under '${SOURCE_FILE_ROOT_IP}/'. Skipping." >&2
        continue
    fi

    # Extract include directories from IP file_info.txt
    incdir_matches=$(echo "$rest_of_line" | grep -oP 'incdir="../../\K[^"]+')

    for incdir in $incdir_matches; do
        if [[ ! -v unique_incdirs["$incdir"] ]]; then
            unique_incdirs["$incdir"]=1
            # Changed: Add to temporary array
            ALL_INCLUDE_DIRS_TEMP+=("-i \"$incdir\"") 
        fi
    done

    # Determine compiler command based on language

    if [[ "$lang" == "verilog" || "$lang" == "systemverilog" ]]; then
        compiler_cmd="\$(XVLOG) \$(XVLOG_OPTS)"
        if [[ "$lang" == "systemverilog" ]]; then
            compiler_cmd+=" -sv"
        fi
        COMPILE_COMMANDS+=("${compiler_cmd} \$(ALL_INCLUDE_DIRS_FOR_ELAB) \"$<\"")
    elif [[ "$lang" == "vhdl" ]]; then
        compiler_cmd="\$(XVHDL) \$(XVHDL_OPTS)"
        COMPILE_COMMANDS+=("${compiler_cmd} \"$<\"")
    elif [[ "$filename" == "glbl.v" ]]; then
        compiler_cmd="\$(XVLOG) \$(XVLOG_OPTS)"
        COMPILE_COMMANDS+=("${compiler_cmd} \"$<\"")
    else
        echo "Warning: Unknown language '$lang' for IP file '$filename'. Skipping." >&2
        continue
    fi



    SOURCE_FILES+=("${actual_filepath}")
    WORK_FILES+=("${SIM_WORK_DIR}/$(basename "${actual_filepath}")")

done < "$FILE_INFO"

# --- Parse sources.f to extract compilation commands for User RTL ---

echo "Parsing $RTL_INFO for user RTL sources and their dependencies..."

# Temporarily store all paths from sources.f to derive unique include directories later
declare -A all_paths_from_sources_f_for_incdirs
all_paths_from_sources_f_for_incdirs_list=() # To maintain order and process unique dirs later

current_main_resolved_file="" # Stores the resolved path of the current main file
while IFS= read -r line; do

    if [[ "$line" =~ ^#.*$ ]]; then
        # Skip comments
        continue
    fi

    # Remove any trailing " I" at the end of the line
    trimmed_line="${line%" I"}"

    trimmed_line=$(echo "$trimmed_line" | xargs) # Remove leading/trailing whitespace
    if [[ -z "$trimmed_line" ]]; then
        continue
    fi
    # Resolve the path relative to ROOT_RTL_DIR
    if [[ "$trimmed_line" == /* ]]; then
        # Absolute path, use as is
        resolved_path="$trimmed_line"
    else
        # Relative path, prepend ROOT_RTL_DIR
        resolved_path=$(realpath -m "${ROOT_RTL_DIR}/${trimmed_line}")
    fi

    # Determine if it's a primary compilation unit
    if [[ ! "$line" =~ ^[[:space:]]+ ]]; then
        # This is a new main file. It definitely needs to be compiled.
        current_main_resolved_file="${resolved_path}"
        DEPENDENCIES_LIST["${current_main_resolved_file}"]="" # Initialize dependencies for this file

        if [[ ! -f "$current_main_resolved_file" ]]; then
            echo "Error: Main RTL file '$current_main_resolved_file' not found. Skipping." >&2
            current_main_resolved_file="" # Reset to avoid attaching dependencies to a non-existent file
            continue
        fi

        SOURCE_FILES+=("${current_main_resolved_file}")
        # Build the Makefile target name for this RTL file.
        # Ensure it's unique and in the 'work' library.
        WORK_FILES+=("${SIM_WORK_DIR}/$(basename "${current_main_resolved_file}")")

        # Determine language and create command for this primary RTL file
        extension="${current_main_resolved_file##*.}"
        compiler_cmd=""
        if [[ "$extension" == "sv" || "$extension" == "v" ]]; then
            compiler_cmd="\$(XVLOG) \$(XVLOG_OPTS)"
        else
            echo "Warning: Unknown extension '$extension' for primary RTL file '$current_main_resolved_file'. Skipping its compilation." >&2
            current_main_resolved_file=""
            continue
        fi
        COMPILE_COMMANDS+=("${compiler_cmd} \$(ALL_INCLUDE_DIRS_FOR_ELAB) \"$<\"")
    elif [[ "$line" =~ I$ ]]; then
        # Add to the list of all paths for include directory extraction
        if [[ ! -v all_paths_from_sources_f_for_incdirs["$resolved_path"] ]]; then
            all_paths_from_sources_f_for_incdirs["$resolved_path"]=1
            all_paths_from_sources_f_for_incdirs_list+=("$resolved_path")
        fi
        # It's an indented dependency line and we have a current main file
        # Add this resolved path to the dependencies for the current main file
        # Changed: Use backslash, newline, tab for readability
        DEPENDENCIES_LIST["${current_main_resolved_file}"]+=" \\"$'\n'$'\t'" ${resolved_path}"
    else

        resolved_path=("${SIM_WORK_DIR}/$(basename "${resolved_path}").touch")

        DEPENDENCIES_LIST["${current_main_resolved_file}"]+=" \\"$'\n'$'\t'" ${resolved_path}"

    fi
done < "$RTL_INFO"

# Now, iterate through all collected paths from sources.f to get unique include directories
# This ensures directories of both primary files and their dependencies are considered for -i.
for path_for_incdir in "${all_paths_from_sources_f_for_incdirs_list[@]}"; do
    dependency_dir=$(dirname "${path_for_incdir}")
    if [[ -d "$dependency_dir" ]]; then
        if [[ ! -v unique_incdirs["$dependency_dir"] ]]; then
            unique_incdirs["$dependency_dir"]=1
            # Changed: Add to temporary array
            ALL_INCLUDE_DIRS_TEMP+=("-i \"$dependency_dir\"")
        fi
    fi
done

ALL_INCLUDE_DIRS=""
if [[ ${#ALL_INCLUDE_DIRS_TEMP[@]} -gt 0 ]]; then
    ALL_INCLUDE_DIRS+="${ALL_INCLUDE_DIRS_TEMP[0]}"
    for ((i=1; i<${#ALL_INCLUDE_DIRS_TEMP[@]}; i++)); do
        ALL_INCLUDE_DIRS+=" \\"$'\n'$'\t'"${ALL_INCLUDE_DIRS_TEMP[$i]}"
    done
fi

# --- Write to Makefile ---

# Add unique include directories as a variable in the Makefile
echo "ALL_INCLUDE_DIRS_FOR_ELAB := ${ALL_INCLUDE_DIRS}" >> "${OUTPUT_MAKEFILE}"
echo "" >> "${OUTPUT_MAKEFILE}"

echo "ALL_COMPILED_SOURCES := \\" >> "${OUTPUT_MAKEFILE}"
for entry in "${WORK_FILES[@]}"; do
    echo $'\t'"${entry}.touch \\" >> "${OUTPUT_MAKEFILE}"
done
# Remove the last backslash if it's there
sed -i '$ s/\\$//' "${OUTPUT_MAKEFILE}" # Remove the last backslash from the last line of ALL_COMPILED_SOURCES
echo "" >> "${OUTPUT_MAKEFILE}"

# Add compilation recipes for each file (IP and RTL)
for i in "${!COMPILE_COMMANDS[@]}"; do
    original_source="${SOURCE_FILES[$i]}"
    current_target_name="${WORK_FILES[$i]}.touch" # Target name for this source
    # Get the dependencies for this specific target
    target_deps=""
    if [[ -v DEPENDENCIES_LIST["${original_source}"] ]]; then
        target_deps="${DEPENDENCIES_LIST[${original_source}]}"
    fi
    # Changed: Add resolved_path of original_source to the target, then target_deps
    echo "${current_target_name}: ${original_source}${target_deps}" >> "${OUTPUT_MAKEFILE}"
    echo $'\t'"@mkdir -p ${SIM_WORK_DIR}" >> "${OUTPUT_MAKEFILE}"
    echo $'\t'"@echo ${COMPILE_COMMANDS[$i]}" >> "${OUTPUT_MAKEFILE}" # Add space at end
    echo $'\t'"@${COMPILE_COMMANDS[$i]} 2>&1 | \\
            tee -a \$(COMPILE_LOG) | \\
		    sed -e 's/^\(WARNING: \[[^]]*\]\)/\$(YELLOW)\1\$(RESET)/g' \\
		        -e 's/^\(ERROR: \[[^]]*\]\)/\$(RED)\1\$(RESET)/g' \\
		        -e 's/^\(INFO: \[[^]]*\]\)/\$(CYAN)\1\$(RESET)/g'; \\
	        if [ \$\${PIPESTATUS[0]} -eq 0 ]; then \\
	        	touch \$@; \\
	        else \\
	        	echo -e \"\$(RED)Error: Failed to compile \$< \$(RESET)\" \\
	        	exit 1; \\
	        fi" >> "${OUTPUT_MAKEFILE}" # Add space at end
    echo "" >> "${OUTPUT_MAKEFILE}"

done

echo "Successfully generated ${OUTPUT_MAKEFILE}."
echo "Run 'make -f ${OUTPUT_MAKEFILE}' to compile and simulate."